[project]
name = "muffin-redis"
version = "3.10.0"
description = "Redis support for Muffin framework."
authors = [{ name = "Kirill Klenov", email = "horneds@gmail.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
keywords = ["redis", "muffin", "asgi", "asyncio"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Framework :: AsyncIO",
]
dependencies = ["muffin", "redis"]

[project.optional-dependencies]
redislite = ["redislite"]

[project.urls]
Homepage = "https://github.com/klen/muffin-redis"
Repository = "https://github.com/klen/muffin-redis"

[dependency-groups]
dev = ["ipdb", "ruff", "pyrefly", "pytest", "pre-commit", "pytest-aio"]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = "muffin_redis"
module-root = ""

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
log_cli = true
addopts = "-lxsv tests.py"
filterwarnings = "ignore::UserWarning:redislite.*"

[tool.pyrefly]
project-includes = ["muffin_redis"]

[tool.ruff]
fix = true
line-length = 100
target-version = "py310"
include = ["*.py", "muffin_redis/**/*.py"]
exclude = [".venv", "docs", "examples"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D",
  "UP",
  "ANN",
  "DJ",
  "EM",
  "RSE",
  "SLF",
  "RET",
  "S101",
  "PLR2004",
  "PLR0912",
  "N804",
  "A003",
  "TRY003",
]
