name: release

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install poetry
        run: pipx install poetry
      - name: Setup poetry
        run: poetry config pypi-token.pypi ${{ secrets.pypi }}
      - name: Build and publish
        run: poetry publish --build
