# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  pull_request:
    branches: [master, develop]

  push:
    branches: [master, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@main
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          cache: poetry

      - name: Setup dependencies
        run: poetry install --with dev --extras redislite

      - name: Lint the code
        run: |
          poetry run mypy
          poetry run ruff check muffin_redis

      - name: Test with pytest
        run: poetry run pytest tests.py
